package lab1;

public class TestedTexts {
    public final static String ENGLISH_TEXT = "That know ask case sex ham dear her spot. Weddings followed the all marianne nor whatever settling. Perhaps six prudent several her had offence. Did had way law dinner square tastes. Recommend concealed yet her procuring see consulted depending. Adieus hunted end plenty are his she afraid. Resources agreement contained propriety applauded neglected use yet." +
            "Is we miles ready he might going. Own books built put civil fully blind fanny. Projection appearance at of admiration no. As he totally cousins warrant besides ashamed do. Therefore by applauded acuteness supported affection it. Except had sex limits county enough the figure former add. Do sang my he next mr soon. It merely waited do unable." +
            "On no twenty spring of in esteem spirit likely estate. Continue new you declared differed learning bringing honoured. At mean mind so upon they rent am walk. Shortly am waiting inhabit smiling he chiefly of in. Lain tore time gone him his dear sure. Fat decisively estimating affronting assistance not. Resolve pursuit regular so calling me. West he plan girl been my then up no." +
            "Betrayed cheerful declared end and. Questions we additions is extremely incommode. Next half add call them eat face. Age lived smile six defer bed their few. Had admitting concluded too behaviour him she. Of death to or to being other." +
            "Written enquire painful ye to offices forming it. Then so does over sent dull on. Likewise offended humoured mrs fat trifling answered. On ye position greatest so desirous. So wound stood guest weeks no terms up ought. By so these am so rapid blush songs begin. Nor but mean time one over." +
            "In as name to here them deny wise this. As rapid woody my he me which. Men but they fail shew just wish next put. Led all visitor musical calling nor her. Within coming figure sex things are. Pretended concluded did repulsive education smallness yet yet described. Had country man his pressed shewing. No gate dare rose he. Eyes year if miss he as upon." +
            "Particular unaffected projection sentiments no my. Music marry as at cause party worth weeks. Saw how marianne graceful dissuade new outlived prospect followed. Uneasy no settle whence nature narrow in afraid. At could merit by keeps child. While dried maids on he of linen in." +
            "Barton waited twenty always repair in within we do. An delighted offending curiosity my is dashwoods at. Boy prosperous increasing surrounded companions her nor advantages sufficient put. John on time down give meet help as of. Him waiting and correct believe now cottage she another. Vexed six shy yet along learn maids her tiled. Through studied shyness evening bed him winding present. Become excuse hardly on my thirty it wanted." +
            "Sentiments two occasional affronting solicitude travelling and one contrasted. Fortune day out married parties. Happiness remainder joy but earnestly for off. Took sold add play may none him few. If as increasing contrasted entreaties be. Now summer who day looked our behind moment coming. Pain son rose more park way that. An stairs as be lovers uneasy." +
            "Ever man are put down his very. And marry may table him avoid. Hard sell it were into it upon. He forbade affixed parties of assured to me windows. Happiness him nor she disposing provision. Add astonished principles precaution yet friendship stimulated literature. State thing might stand one his plate. Offending or extremity therefore so difficult he on provision. Tended depart turned not are.";
    public final static String FINNISH_TEXT = "Vatvotusta vietavaksi sen eli paaltapain ansioitaan tyttarensa kun. Ne kesy ajat tosi emma en eika te mika ja. Voidaan lankkua et mitenka ei en no tulossa. Sittenkuin palkkioksi nuottikota vai han. Tarpeeksi tarkoitat antamatta ei ja kasvoilla. Ota isantain talvella vai vanhasta kirkolle pienessa iso mahtanee. Hokee jokin me ennen te akkia kesan. Kay menemaan ostettua rakentaa olisivat tuo. Mahtanee vie oma lyhyesti istuivat saavansa." +
            "On te ei kurkkuun ennenkin pohjassa en rakentaa. Kertoi heitti laskee he paansa ai et omille. Vai ensi mita pera pain yha vaan tein. Kaksikaan eli saa riittaisi laineilla arentinsa sentahden sen. Ota ero oma hiisi luo korko mutta. Soderling ei olevinaan se mitapahan on uteliaina raastavat. Mitas sumun ota sinne ela pursi kylla jaa. Miellyttaa naamallasi on ja puutavaraa ja ai. Han jolloin vie hymahti ole pilalla ota." +
            "Ne mita ryit aiti ai. Hokee yha kas olipa loi nyt muuta. Liikaa se jatkoi ei raakun en kuulee me elatte senkin. Jalkeensa toivotaan tarvitsen ajattelee ryyppasin ai ei. Ruuhessa se on kesaisin olisihan ne tarkkaan. Tuloja se paljoa saalla ei ne. Antakoon kalastus ei he on no tuulella." +
            "Tuo sai juova oli meren voi ulvoo. Antia no ja he nehan minun ja juotu menna sinun. Silmat sen mitaan emanta toisia han. Puskisi eri nalasta tuo merille silloin vie talloin. Jaksa mutta se sanan tulet se sinne. Anastaa jo ja antakaa samassa sisassa silmain ei. Tai pian alas saat vaan vai apua alla. En tuli toki omaa saat te on ajat. Ankkuri ei soittaa tulevan ne pujahti jo. Ulkona saakin hintaa toi jai kun vesien iso." +
            "Ei jo paaltapain vastapaata rikastunut nykyaikana en no tyttarensa. Helga iso satoi rupee oli siina. Porstuan ja ja kurkkuun ymmartaa en luuletko. On he loytamaan kerrankin ei ei kasvoista olevinasi punastuen tyrskahti. Pyyhkaisee se mielellaan kymmeneksi kulkuneuvo ai on jo. Isa paranevan tee oli ukkovaari kuvitella semmoinen." +
            "Mita ai emma en et enka. Saat naki luo jaa ajat kas jai. Jalkaansa jo riittaisi vanhoiksi ai jalkeensa puuskahti rojottaen. Ikkunasta maistuisi rikkaiksi asiakseen kasvoilla nyt riittaisi eri toi. Niin kayn ei koli et ulos. Tapahtua lehmanne pystyssa isa ota voi. Laiva suusi et olisi hahah hyvan satun ne. Tuhrinut jai saisitte luo kun antamaan ole tarvitsi. Ne ja ryypannyt et puuskahti millainen ai. Mika siis voi vaan jata vesi isa nae jos hymy." +
            "Se huumauksen ne se mielellaan onnestanne uteliaasti te. Saattoi ota heraten sen saa ihmisia jauhoja. Ota kayn meri olin kuin ehka vie kuka vei sen. Et antautuen torpparit toivotaan asiakseen ajattelee kunnialla jo. Kenkia ei sarkee no ei siella konsti. Saa kunnialla toivotaan kaantynyt kaakkyroi unhottako vai laineilla. En osta eika syva me ei etko joku." +
            "Laivat verkot han taisin nyt tuossa ryhtya luo. Menettelet pilkkanaan kysymyksen isa mielellaan harrykoita tarkastaen toi. Puhkesi kelpasi saattoi on he kykenee ne ilmassa. Muilla olivat hatana hiljaa pilaan jos tapana tuo. Opastaa vieraan ainakin ollessa talloin saa sen kai kas. Kas juon yhta luo teki nyt. Lahjaa paivaa nimeni ero jaa saivat kuinka vaikka kun. Lypsaa voi niskaa voivat sarkee myrsky tahdot ota. Ja kirkossa on tyttokin en en keinolla paattaen." +
            "Mieli saata tai puhui antia voi hanhi pappi iso vie. Tulee ai menee kalaa moisi jo ja tekin. Valiin sen pitava sen vapaus lypsaa vei tikkua. Pain sika on se kuin ne. Jo me te tupansa tuvasta peralla ne kynansa. Aallokkoon ja puutavaraa et karahtanut kummeleita jo tarkastaen rukoukseni. Pitka kai pyori jos nakyi. Moottori vanhasta ai koettaen vieraita kolmanna ei. He en esimerkkia ne on tulisikaan kerrallaan nykyaikana." +
            "Saa vietavaksi hartioilla eli ankkurinne nae lahetakaan tyttarensa kaupunkien. Parempaa vai nyt tuo kalastus kaivanut osa toivoisi keinolla. Ilmassa totisen raiskaa han tulevan jutkaus jos iso nyt. Tarkoin mistaan hylkeet ai ujostus ai maistaa et ja milloin. Ne on emme enka kone ai no joka. Niinkuin isantain toisessa ai se se. Te valmiiksi muutamata se jo rihmoihin kaikkiaan tarvitsen. Aiti on naki pida on ei ai pain osaa. Kai osa varmuuden saaliista ela ajelehtii. On se tyhjan syntyi ilmaan.";
    public final static String GERMAN_TEXT = "Eigenes tal spiegel man niedere all. Richtete ruh trostlos konntest gesprach wie freundes. Hergab mensch bitter en in bliebe ja sachte. Freilich te he um feinsten kraftlos du. Was blo begehrte ihr gegessen eberhard gespielt. Himmel diesen gesagt person am um. Saubere klopfen niemand ku raschen ei blickte an in. Regungslos schuchtern ku schuttelte nettigkeit zu la freundlich nachmittag ja." +
            "Wartete glatten konnten ansehen spruche zog gib anblick. Halboffene ob birkendose ubelnehmen ri du todesfalle ei handarbeit. Bei hinstellte hut mancherlei begleitete. Woher brief aus hosen alles tat kenne knapp. Turnhalle unendlich he bi uberhaupt verwegene liebevoll da ab schreiben. Rief nein bist mich das gewu mehr ach. Wahr tale name wu denk da fest. Gegen weste viele heute da zu es schon." +
            "Im wo schoner filzhut samstag sonntag so dichten. Gut verdrossen das handarbeit erkundigte neidgefuhl. Magdebett rausperte windstill es du geheimnis en gewandert da klimperte. Drei ehe weit und hast wert bart aber ich. Rausperte gegenteil arbeitete tat wie angerufen schlanken. Preisen wo je achtete unrecht da diesmal em schoner steilen. Argerte von geschah fischen nur ihr kleines ins." +
            "Zu te enden eines allen junge empor leute bi. Boden tun des nun aus enden alles dabei. Mi verlogen vorwarts manchmal richtete wo prachtig du zu. Lauschte verlogen zu mu unbeirrt. Te um genug gutes wobei boden wills ob he. Da schreibt ubrigens schlecht se zu gefunden ri lauschte gerochen. Nachtessen dachkammer la es ob aufzulosen ku. Grasplatz bi schranken magdebett in dammerung vorbeugte. Erkundigte von gut halboffene was gesprachig grashalden zaunpfahle feierabend. Sa durchs ochsen halber wo hauses hangen da kaffee." +
            "Zahne wu horst dabei ei deine kenne ab he tisch. So brachte dunklen drunten gewohnt richtig eigenes da da. Ubers vater er wills herrn se gluck ihrer es. Senkrecht verweilen ei sa wo ertastete du. Geh will hoch den ans nach dich gehe. Nie geholfen blattern freundes zum und. Knapp du darin regen se in. Ubelnehmen es regungslos nachmittag lattenzaun ja bi hereintrat an verbergend. Stehen gut das dachte bat eck nieder. Zwirn gab stamm leute die hinab stand." +
            "Ja in zu unbemerkt schwachem zu uberhaupt. Diesem feucht dachte bi laufen begann wisset im es in. Plaudernd an eintreten ja mitwisser tanzmusik. Haus grob wenn lich duse gott oha weg. Sehet angst blies jahre komme eck bei man. Ob schurze da standen bereits zu da. Dabei sto hande leber die ernst sehen was. Das eleganz ihn tod dichten klopfen beschlo schoner nie alsbald. Wenns von hof jeden das ein nacht." +
            "Fu en leuchtete du verwegene nachgehen la kindliche zierliche. Pa erschrak hinunter zwischen nirgends zu en ratloses. Die fur herde abend als gehen adieu danke. Grad frau aber bis sei ruth. Langsam wahrend heiland da richten sa bedeckt leuchte wo ja. Ist lohgruben furchtete betrubtes nur sudwesten ausgeruht ausdenken. Ferne namen denen regen lag nie davon naher. Bilderbuch dir erkundigte fluchtigen aus geschwatzt zaunpfahle wie. Das besonderes vertreiben hut grashalden fur aneinander ihr." +
            "Ganz tat den sag alle was leid. Als leben uhr blatt das litze. Dach bart da habe oder wu ding. In eleganz tadelte blickte la pfeifen ab ei bruchig. Unterwegs ihr bat das bedeckten gestrigen. Den erkundigte betrachtet federdecke sie bescheiden drechslers gerbersteg. Lampe genie steht alter hut gru heran. Magdebett bi leuchtete aufraumen um verharrte te ja verstehen. Erzahl ruhmte meinte als las." +
            "Acht sind wenn flei gibt lang du la so. Tut fragte des kummer lachte wiegte gro seiest soviel. Gro drunten solchen gewerbe uhr. Ewige sagst pfiff getan war gro lampe sagte. Belustigt mannsbild vergnugen schwarzes da ja es stadtchen gescheite mi. Funkelte neunzehn verstand mag ton neustadt tat talseite das. Ein schranken was kindliche bat gestorben." +
            "Gebracht vollbart vorstadt da ziemlich gemessen ei lachelte so zu. Augen keine heran ja he. Sag tod ort setzte kannte ist sohlen. An bodenlosen so knabenhaft grundstuck bi aneinander se. Gefallt ahnlich diesmal bi es pfeifen richten um sonntag. Begru kam las dahin statt. Anzug holen da bi still ob viere so damit. Ri wo eigentlich zu en kuchenture vertreiben erhaltenen. Was beiden kummer rothfu lehren ist mag nur.";
    public final static String ITALIAN_TEXT = "Mia prende alzata hai vorrei gli fai rapiva svelta. Bocca si ti quale avevo ed mette siamo donne. Te pietre petali el lo di roccia. Ben chiamasti fai chi soggiunse rifiutare vai. Neghi perde puo sua passa hai certe via steso magra. Sembrava affinita coronata seguente giardino suo non smettere ero. Io ai nuca mite la agli nevi tebe voce. Dominio tu cerulea da avidita." +
            "Qua sofferenza silenziosa cancellato mio sia turbamento. Affluisce dimagrato levandosi disegnato hai nei per. Uno dovevamo ora uso troverai esitanza ove. Or sfaldavano sospettoso vi padronanza bellissima ha io. Dormissero qua inebriarti stanchezza fra amo implorando. Com copriva pollici cio sta settala. Rosa ben modo dare vene armi ali. Ecco esce fede fa tuoi il ne. Strazii sia nel stasera passava turbini. Un bruciava oscurato la orgoglio lo virtuoso." +
            "Grazie in oh el se vivere uscire. Eleganza crudelta sui all impronta. Fa so mani vita vedo vene. Io rinnovati lasciarmi interiori fa abbassano fu riempiono. Pel annunziare non incertezza par tranquilla dio. Pungeva ve insieme vi inchino. Si vedi lo al fame bell vede. Cavallo le el mi sospesa da rianimo." +
            "Mamma nel sai esser non veste. Rivedervi ornamento attendeva sta deliziosa uno sensitive passaggio. Far gli improvviso sai impazienza noi sorridente baciandola conoscermi portartela. Quei aver dove riva devi via sia nudi mia. Veniva the quando due rapida perche all mentre. Me te grave sapro genio ho basso denti." +
            "Ribollisse sormontare sbigottita incomincio si re. Posso valsa al el stavi copto verro forme. Eri sei entrambi preziosa trapassi sai speranze piramide migliore. Difesa te pieghi eguale quarta capace fa depone. Fu pensa tutto il caldo della. Primo possa marmi ve va el parso ch." +
            "Cercarla possente vorresti assalito che dai risoluto maschera. Rispetto ostinata scolpire poi giardino sta dei nel. Oh ho povero vedere vicino si tempia vi vivere. Ex oh aspiro ha divina appena sapevi veglie monaco. Certezza sofferte chiamata suo eviterai sai volgersi. Rapimento sue pur all perplesso comperato tuo. Ergendosi accendeva per liberarti gia respirato abbandona del." +
            "Re paragone creatura acerbita ai guardava lasciami vi. Entro tue forza miele mazzo per pur oltre sul. Lo ti il gabbie quanto lancio. Fato mare arme tu anch vi mine riso. Poi affannata ami cresciuto melagrani una abbandona brillanti. Far aspettando nel voluttuosa sei turbamento tra. Grappoli tuo inquieta cio orribile dissolve scoperto. Alzeremo voi parlando pei qualcuno serbatoi mio bellezza. Impregnato voi san esaltavano dal dal sfaldavano." +
            "Pensavo copriva conosco una non cattivo tal. Uno distrutta osi desiderio era soffocato benedetto vertigine talismani dov. Giu dal ricuperata aggiungera silenziosa impazienza. Scorato chinava tuo lei bisogno. Udissi affina piu cui nemica spalle non. The ben ergendosi impudente sconvolge. Ritrovata deliziosa consolato io la rivederci la. Sai cairo tue molle mirti copia." +
            "Nel nascondere dal una toglieremo ricordarmi impazienza. Fresche arteria ha le giacche miniato. Fa te omeri notti saffo dagli volle parli. Tal conservo turchese dal plasmare cui. Mai puo sete quel all tuo caro. Abisso membra ve vi ma queste. Abbozzata cio necessita riconobbe cui mie sui. Coraggiose bel impazienza sei scomparire qua ricomincia partissero." +
            "Ed ve difenderlo tranquilla conoscerla scacciarla po fu interrotta. Tocco voi dagli fondo una parla. Cercarla ha di negativa campagna da eviterai. Se te guardando custodiva ed ha riconobbe repentina abbozzata affatichi. Immutabile re ritornarvi appartiene elefantina un oh ve. Che deliziose tra mia affatichi disponeva piuttosto.";
    public final static String POLISH_TEXT = "Puste gospodarskiéj mowę chcę wiele trzej jedna wykli barbarzyństwa opoka prapradziadów. Zakryła dążył nosy Zaś jaki Jest trzy Przy Wiec myślami pływać konikach majowéj ryby. Najpiękniejszego izba Rzeczypospolitéj smyk domu Kogo najpiękniejszéj Mamy rąk Znam. Dziki rosciągnionemi ganku dojeżdżaczów panie biegu płot nauki siano Worończańskim czém marszałkowską Dojeżdżaczowi. Czasu lisem Zgody lekka Kościuszkowskie oknie nierostrzygniony bryki najpiękniejszym Niesiołowskiemu koszt ogary żołniersczyzny. Zdala daczy Niesiołowskiemu najpiękniejszym tamek Kościuszkowskie nierostrzygniony bicia Cóż zwady pała żołniersczyzny czemu. Znowu Białopiotrowiczowi bitwy izbie drzew pędu." +
            "Krzyk mniej niech Daruj Białopiotrowiczowi Iść. Jedna Rzeczypospolitéj Wtém Najpiękniejszego dwoma najpiękniejszéj progu matki. Inna kołysał szyb syna Albo spod schwytać gniazdami Wprawdzie Niewielki Wiec. Lokaj dniem matki ptaki dawno psina drogo wódz. Żołniersczyzny nierostrzygniony Kościuszkowskie morzu dzika póki dół najpiękniejszym. Łoś Rzeczypospolitéj krzyk danie Witaj nasza najpiękniejszéj Najpiękniejszego nocą. Samym ukazy domie gęstość łotr Stryjaszek żyć niepoznasz trzej wywrócony Było trany." +
            "Upięknił lekki włościan Czyż danie domysłów biję skarb. Płot nudzi przestępując uczty Roskrzyżował rzeźbiarstwie mały raczy chart Krzyk wpółgłośne Może. Białopiotrowiczem gości murami Któż ogonie. Idę Lecz ncci Dzik dał. Opoka danie przestawał czarniutkie Dziś modna drewnianéj. Litewskich powtarzał ryby pary inne strwożone świątyń mię niż roju. Turka Daruj Twoja druki wybor astry. Zaszyt szyją ucałowawszy starym przecisnąć obaczy kocham Bernatowicze wierzchołki Alpów." +
            "Dobrze Najpiękniejszego najpiękniejszéj szyją kórki Rzeczypospolitéj strony Słowo papier. Najpiękniejszego bitwie muzyce najpiękniejszéj pływa Nagła żydzi rosną Rzeczypospolitéj. Szyję komplementy swoją ziarna ukryte moskiewskie dosiedzieć Ażeby nowych Niemieszał przesądów liść Sprawa. Białopiotrowiczem gada mię domu poda Duma. Rzecze suchym papier powód mówcy. Uparta dojeżdżaczów rosciągnionych zboża wielki Wyczha Przysiągłbyś Bezładnością przejrzystość powiem. Boku wiek Duma niewielkim scen zawrócił rana gotyckiéj. Cary tył rano izby temu Tyle kart Białopiotrowiczowi Jéj. Ciemnozieloném Herb twą bezprzykładną Bezładnością Obok izby rąk zwierciadlanéj rosciągnionych. Stały jakoby szafie murami Mniéj nieodstąpił nadstawiając drudzy wojska skrzydełkami." +
            "Odpowiedział strzeleckiemu cudem Odstrychnęli trzykrólskie spraw kroku Zazdroszczono Odsłaniając rodzi. Być ucha pili Bóg wozy Białopiotrowiczowi. Brat cugi Białopiotrowiczowi czem mego kity kozy. Pana Białopiotrowiczem lasy tace mimo. Rzeczypospolitéj ncci Najpiękniejszego najpiękniejszéj trzy Mój gaju. Desce czyje nisko bicia Podniesione wieczornego chuć posiedzenie dawno pierścień daczy. Jest ncci dwie Białopiotrowiczowi pól coś. Białopiotrowiczowi taż Kosy weń mszy przy siwy. Niesiołowskiemu nierostrzygniony żołniersczyzny Gotem kiedy panek chowa Kościuszkowskie." +
            "Cugi kara ramy nierostrzygniony sali Niesiołowskiemu razy okna zaś Kościuszkowskie żołniersczyzny kawy. Czyli Najpiękniejszego Rzeczypospolitéj niéj wiary sług najpiękniejszéj wyrok. Boga boku przyzwoitość zacietrzewiony nieszczęście roskrzyżował komu ruch ucha odpowiedziéć. Przestanku plan zobaczenia sama piki urządzał złośliwe okno byli zaludniono. Moskal nieogłodzą posłańców Bernatowicze brzegu chartu zwierciadeł całym Wyrządziła. Przechrzciłby zboże mógł szczególniéj suknia ubóstwiałbym lubię rozmaitością puszcz potraw Kibić wyciągniętą." +
            "Sił gdzieniegdzie Grad Grom powróciłaś zacz Wykrzykników Lombardskiém obok przestraszone. Piramidy jakim urzędem Okiem samą Zwano Lilia wybor dworu nóż paszczę. Czas wali boru mimo miny gwar. Niesiołowski kędy roztargnieniu myśliwskiém opoka jakby poprzysiągł drzew śmiertelnego. Tkany orzę dawni wicin kopie ulice Podkomorzemu okien Rospływały Jegermajster Wstrzymując Jedna. Cichy jałowcowym daczy Latem dziwi rozgoworów Całe utrzymywał pilni. Posępną jednej trzoda sposobić zachodzie można dowód kurów powód ojczystą stojącą zdały." +
            "Zboże charty beczek chwali gadać spodem Białopiotrowiczowi powiem placka. Jakim Białopiotrowiczowi stara cóż Forum lancy wieku pewni. Izbach spisem Białopiotrowiczem drobne ubrana. Cudem mamę figurując jedli Twych Przed dobry Przyszedł rachunków wzory gdyby. Nosie konno uwagi echem Białopiotrowiczowi. Cudzy duszy toczy wodza żołniersczyzny nierostrzygniony Niesiołowskiemu panie najpiękniejszym." +
            "Byle Wielkiego młodzian tace przy refektarz zwierzyny izba téj lica uczy. Wojny udać dajem utrzymywał przysłowie przestrzeni Przez Otoż łowy dokumentów Sień Kniaziewiez ustaw. Obmoczyłem Kusy Przyjechał przeprosić uszy daje ptak był niż przestworzu. Brał kopie psów owiec przez sercu dniem. Wiatr licem zapadło kąpieli progi ogary Zgoda wiary Napoleon karjulka tańcach. Bóg szli chce Tłumacząc piki brząknął post słaniając skrzypiące ramy Zbyt. Najpiękniejszym nierostrzygniony Szabli lubił Majora żołniersczyzny jakże młode stała garnie Kościuszkowskie. Grafie chleba wzrost nauką. Przypadkiem owocne obicia uczciwość także niezasnąć słyszałem bratni włók wzrost lepsza. Chude Najpiękniejszego sercu bramy góry stary najpiękniejszéj Rzeczypospolitéj czuł." +
            "Areszt Nalał liczba gęsto biedak Kusego. Latach Kościuszkowskie całym stoła znaczy żołniersczyzny stół niebie Niesiołowskiemu liść Rymsza. Rada ciekawemi mnie puer inne poważnie balu fali Grom piersiach. Zwolna Wojska huczą wstydu. Sądu wódz swój porównywać nisko wtém Rostargniony Stado przetknięto Wtém niesłyszano owoce częstokroć niezaczynał. Szczęśliwsza nieuszanowanie Lasami iskier odpowiedziéć dumać przestępując prapradziadów Waść płaci. Pani ryby daje ryki poda roztargnieniu mego Ściągnęły Przeprosiwszy Tyle rozłożystym Podkomorzanki farb podziękować.";
    public final static String SPANISH_TEXT = "Hay concetti adquirio paseaban mas recordar primeros necesito. De arte es ma reia musa da alto boga luto. Ahogandose propositos esa luz exclamaron calcetines tropezaron las. Afines siglos hurana ver con panera era. Te tenerle le grandes siempre es el resulto absurdo. Fue ahogarse titubear las relativo. Isturiz ma delgado oh caseria sr andando. Como alma que fino azar mas." +
            "Aqui capa flor raro yo la raso ropa. Vulgares valiosas ve os inferior blancura lenguaje cornetin. Eh contaduria compadecia el honestidad despertaba un. Del intensidad escudrinar pentagrama pastosidad ser tio. Tardo oh tu te prima tanto yo. Que chillona sollozos vez entonces deliraba por sea. Exigir orejas regalo piedad dinero pre que vez. So afan alla foro dado arte frio he. Pormenor del capricho encantos chillona incienso don ingresar." +
            "Senora ya su yo oh cierta teatro moscas paloma. Fosa loza cola ama moro esa paga eso. Pan rey gentilica van ley maniatico estuviera costumbre. Cementerio sacamuelas castrillos aconsejado mal encontrado dio. Agua cafe ello seca el de al vano. Enguantada partituras por adulterios iba correccion los mal admiracion. Atras el sobre ha so deseo aguas dedos ha. Direccion actitudes ya esplendor soberania ch dirigirle si insultaba. Gato en eran de fija ceno alto." +
            "Estarias lo quiebras encogido lo. Tarde el pedir ma el luego flaca. Retroceso discursos estrechar del arruinado vio fioriture. Buscarlos si ofenderla acompanar ir. Carcel guerra fijeza sin hierro cuadro marido que. Musa juan tan chi agua sano cosa esta las. Soy grissi del serias ocioso tio altura escena. Corte vicio cinco dio resto dar mujer palco oro. Tristes asi recordo mia dos energia aquella cuentas. Mar servicio pre pareceis realidad por desairar vinieran italiana." +
            "Escaparse mentecato don gas necesidad contraria torrentes distraigo. Dar alambicada sol chillerias animandose ley. Alambicado il menudeaban desiguales si abofeteado sacramento propositos. Me su inclinaba animacion se idolatria. Tentacion suo hoy artistica non enfermero. Los armado rio acosto fregar chiste cortes. Visto estoy mal ido tio pan campo duros clara." +
            "Cuyo arte ha supo pero le este dama ir tu. Despertado titiritero confidente le lechuguino he ordinarios. Ti sellado antiguo un acababa ceguera si da aureola. Ma seduciendo la compadecia he condenasen. Circulo extrana pequeno haberle ma sonrisa no. Tenia asi pasto hoy una tardo doy. Vanidad hembras acababa he gozaban cuentas sr. Extrana oro muy del ahi encogia tenerla. Comodas sus plateas opinion dos gracias." +
            "Consuela lo salvador desafiar fugitivo se yo pimiento el. Uso vez rio carisimo caracter estarian aburrida. Apoplejia esa fantasmas doncellas iba devolvere oro enfermero reintegra. Molestarle del encontraba miserables oyo mal empresario ley. Entrego tablado envidia mil con vuelven uno reditos. Manana adusto tomado mil uno guerra eso oir. Contribuia tristisimo aseguraban la soplandose de il. Ricos era los mia sueno grima asi. Mia urbana cuarta rey tantos estuvo osadia." +
            "Empenarse pulcritud da no despierta rectifico direccion eh. Ya graves varios llaves fe ribera. Versos rey queria dudoso siglos chi huesos muelle. No animandose desencanto adivinarle da un el. Encontrase va no aprovechar si alumbraban hablandose ma. De mayordomo oh procuraba un nerviosas mentecato no." +
            "Era escaparme fin fue repulsiva preterita. Ella esas al para fe ir paga. Oh ha la buscar su benito tierra podido debido lozana. Flexible oh en cantaron la ni tesorero. Opto creo pide nada era tres sus. Presento el volverse de clientes. Sin creencia don amandose ser instinto cuestion continuo prosaica." +
            "Tercer ex cuenta alguna tu vestia trampa. Ropa dar chi uno hubo eres. Lucia vamos taner buono el al. Yo disparates un extranjera gentilicio compadecia sacramento la aconsejado. Ese alambicada constituia por ingratitud. Tengo actos yo fiaba se abono novia media. Cortada sol muy materna sacarlo son parezca. Su unia en el sana nada pelo otro.";
}
